---
title: "1-EDA"
author: "Janith Wanniarachchi"
date: "3/11/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(warning = FALSE,message = FALSE)
```

```{r}
library(tidyverse)
library(rpart)
library(randomForest)
library(MLmetrics)
```


```{r}
preprocess <- function(tib,test=FALSE){
  date_columns <- c("Expected_checkin","Expected_checkout","Booking_date")
  tib <- tib %>% 
    mutate_at(vars(contains(date_columns)),~ as.Date(.x,format="%m/%d/%Y")) %>% 
    mutate_if(is.character,factor) %>% 
    mutate(Lag = as.numeric(Expected_checkin - Booking_date,units="days"),
           Duration = as.numeric(Expected_checkout - Expected_checkin,units="days")) %>% 
    select(-all_of(date_columns)) %>% 
    mutate(Income_number = case_when(
      Income == "<25K" ~ 25000,
      Income == ">100K" ~ 100000,
      Income == "25K --50K" ~ 37500,
      Income == "50K -- 100K" ~ 75000
    ),
    Cost = Duration * Room_Rate,
    Cost_Income = Cost / Income_number,
    Visit_Cancel = factor(case_when(
      Visted_Previously == "Yes" & Previous_Cancellations == "Yes" ~ "Visit_n_Cancel",
      Visted_Previously == "Yes" & Previous_Cancellations == "No" ~ "Visit_n_No_Cancel",
      Visted_Previously == "No" & Previous_Cancellations == "Yes" ~ "No_Visit_n_Cancel",
      Visted_Previously == "No" & Previous_Cancellations == "No" ~ "No_Visit_n_No_Cancel",
    )),
    Total_PAX = Adults + Babies + Children,
    N_Minors = Babies + Children) 
  # cat_cols <- tib %>% select_if(is.factor) %>% colnames()
  # cat_cols_keep <- c("Meal_Type","Deposit_type","Reservation_Status")
  # cat_cols_rmv <- cat_cols[!(cat_cols %in% cat_cols_keep)]
    # final_vars <- c("Meal")
  # tib <- tib %>% select(all_of())
  if(!test){
    tib <- tib %>% 
      select(-`Reservation-id`) %>% 
      mutate(Reservation_Status = factor(Reservation_Status,
                                         levels=c("Check-In","Canceled","No-Show")))
  }
  tib 
}
```

```{r}
train <- read_csv("../../data/Hotel-A-train.csv") %>% preprocess()
test <- read_csv("../../data/Hotel-A-test.csv") %>% preprocess(test=TRUE)
valid <- read_csv("../../data/Hotel-A-validation.csv") %>% preprocess()
# train %>% write_csv("../../data/processed/train_preproc.csv")
# test %>% write_csv("../../data/processed/test_preproc.csv")
# valid %>% write_csv("../../data/processed/valid_preproc.csv")
```

```{r}
glimpse(train)
```


```{r}
table(train$Reservation_Status) / nrow(train)
table(valid$Reservation_Status) / nrow(valid)
```

```{r}
skimr::skim(train)
```

```{r}
cat_cols <- train %>% select_if(is.factor) %>% colnames()
map_dfr(cat_cols, function(x){
  pval <- table(train[[x]],train$Reservation_Status) %>% summary() %>% .$p.value  
  return(list(column = x,rejected = pval < 0.05))
}) %>% filter(rejected == TRUE)
```

```{r}
# cols <- c(train %>% select_if(~ is.factor(.x)) %>% colnames(),"Reservation_Status")
# GGally::ggpairs(train %>% select(all_of(cols)),
#                 aes(color=Reservation_Status,alpha=0.2),progress = FALSE)
# ggsave("outputs/pair_plot_colored.jpg",width = 841,height = 594,units = "mm")
```

```{r}
library(ggfortify)
pca_res <- prcomp(train %>% select_if(is.numeric), scale. = TRUE)
autoplot(pca_res, data = train, colour = 'Reservation_Status')
```


```{r}
# TODO insert evaluation pipeline here
```

```{r}
model <- randomForest(Reservation_Status ~ .,data=train)
```

```{r}
plot_importances <- function(model){
  imp <- importance(model)
  imp %>% 
    as_tibble() %>% 
    mutate(variable = factor(rownames(imp))) %>% 
    arrange(-MeanDecreaseGini) %>% 
    mutate(variable = fct_reorder(variable,MeanDecreaseGini)) %>% 
  ggplot(aes(x = variable,y=MeanDecreaseGini)) + 
    geom_col()+
    coord_flip()
}
plot_importances(model)
```


```{r}
evaluate <- function(y_preds,y_true){
  print(ConfusionMatrix(y_preds,y_true))
  print(F1_Score(y_preds,y_true))
  print(Precision(y_preds,y_true))
  print(Recall(y_preds,y_true))
  print(caret::confusionMatrix(y_preds,reference=y_true,mode="everything"))
}
```

```{r}
y_preds <- predict(model,newdata=valid %>% select(-Reservation_Status))
evaluate(y_preds,valid$Reservation_Status)
```


```{r}
make_submission <- function(test_preds,name){
  submission <- tibble(`Reservation-id` = test$`Reservation-id`,
                       Reservation_status = test_preds)
  submission %>% write_csv(paste("../../data/submissions/",name,"-",Sys.time(),".csv"))
}
```

```{r}
test_preds <- predict(model,newdata = test)
make_submission(as.numeric(test_preds),"naive")
```

